#include "IceObjectMessageIDs.h"

namespace Ice
{
	TEXTID_BEGIN_DEF(aObjectMessageIDs)
	TEXTID_DEFINE_CONSTANT(MOVER_START)
	TEXTID_DEFINE_CONSTANT(MOVER_END)
	TEXTID_DEFINE_CONSTANT(MOVER_PASSING_KEY)
	TEXTID_DEFINE_CONSTANT(ENTER_FPS_MODE)
	TEXTID_DEFINE_CONSTANT(LEAVE_FPS_MODE)
	TEXTID_DEFINE_CONSTANT(START_JUMP)
	TEXTID_DEFINE_CONSTANT(END_JUMP)
	TEXTID_DEFINE_CONSTANT(TRIGGER_LEAVE)
	TEXTID_DEFINE_CONSTANT(TRIGGER_ENTER)
	TEXTID_DEFINE_CONSTANT(INPUT_START_JUMP)
	TEXTID_DEFINE_CONSTANT(UPDATE_CHARACTER_MOVEMENTSTATE)
	TEXTID_DEFINE_CONSTANT(ENTER_MOVEMENT_STATE)
	TEXTID_DEFINE_CONSTANT(LEAVE_MOVEMENT_STATE)
	TEXTID_DEFINE_CONSTANT(CHARACTER_KILL)
	TEXTID_DEFINE_CONSTANT(CHARACTER_COLLISION)
	TEXTID_DEFINE_CONSTANT(INTERN_RESET)
	TEXTID_END_DEF
	
	TextID& getObjectMessageIDs()
	{
		static TextID theOneAndOnly(aObjectMessageIDs, OBJECT_MESSAGE_ID_SIZE, TEXTID_DEFS_SIZE(aObjectMessageIDs));
		return theOneAndOnly;
	}
}